[[pages]]
name = "Matricula"
icon = ":mortar_board:"
is_section = true  # This is a section

[[pages]]
name = "Información"
path = "pages/matriculados.py"


[[pages]]
name = "Segunda Lengua"
icon = ":books:"
is_section = true

[[pages]]
name= "Nivel de segunda lengua"
path = "pages/nivel_grados.py"




